feat(trending): カード(中)の実装
camp-team/team-training pull request #21
Opened 2020-07-26 09:52 UTC by kkkkoki

カード中の実装をしました。
ご確認よろしくお願い致します。

## PC
![image](https://user-images.githubusercontent.com/65912888/88476142-0deb4d00-cf71-11ea-828b-dd6cf2cd43dc.png)

## SP
![image](https://user-images.githubusercontent.com/65912888/88476128-db415480-cf70-11ea-90f7-96f494789653.png)

2020-07-26 10:01 UTC, dninomiya commented on src/app/trending/trending.component.html
> +        <div class="card__cover card__cover--image-1"></div>
modifier じゃなくて htmlにインラインで背景指定

2020-07-26 10:01 UTC, dninomiya commented on src/app/trending/trending.component.html
> +          <p class="card__title">Dolore magna aliqua</p>
h3

2020-07-26 10:01 UTC, dninomiya commented on src/app/trending/trending.component.html
> +            </svg>
`<img  src="assets/xxx.svg">`

2020-07-26 10:01 UTC, dninomiya commented on src/app/trending/trending.component.html
> +    <div class="card desk-top">
desktop-only

2020-07-26 10:01 UTC, dninomiya commented on src/app/trending/trending.component.scss
> +    background-position: center center;
center

2020-07-26 10:01 UTC, dninomiya commented on src/app/trending/trending.component.scss
> +    }
inline

2020-07-26 10:01 UTC, deerboy commented on src/app/trending/trending.component.scss
> +.flex {
レイアウトまわりは除去

2020-07-26 10:06 UTC, deerboy commented on src/app/trending/trending.component.scss
> +    margin-bottom: 4px;
10px

2020-07-26 10:06 UTC, deerboy commented on src/app/trending/trending.component.scss
> +    margin-bottom: 4px;
行間20px

2020-07-26 10:06 UTC, deerboy commented on src/app/trending/trending.component.scss
> +    font-size: 13px;
行間抜けている

2020-07-26 10:06 UTC, deerboy commented on src/app/trending/trending.component.scss
> +    padding-bottom: 180px;
`padding-bottom: calc(180/360 * 100%)`

2020-07-26 19:21 UTC, kkkkoki commented
修正しましたので、ご確認よろしくお願い致します。

**主な修正内容** 
- クラス名の変更
- レイアウト周りの削除 https://github.com/camp-team/team-training/pull/21#discussion_r460506633 、https://github.com/camp-team/team-training/pull/21#discussion_r460506422
- カードタイトルをh3に変更 https://github.com/camp-team/team-training/pull/21#discussion_r460506236
- SVG画像の直書きをファイル呼び出しに修正 https://github.com/camp-team/team-training/pull/21#discussion_r460506297
- coverの背景画像をhtmlで記述 https://github.com/camp-team/team-training/pull/21#discussion_r460506200
- スタイル修正( 
margin10pxに修正 https://github.com/camp-team/team-training/pull/21#discussion_r460506733 、
coverのpadding修正 https://github.com/camp-team/team-training/pull/21#discussion_r460507086 、
行間の追加修正 https://github.com/camp-team/team-training/pull/21#discussion_r460506756 https://github.com/camp-team/team-training/pull/21#discussion_r460506835 )

## PC
![image](https://user-images.githubusercontent.com/65912888/88487225-203fa800-cfbe-11ea-8b61-53c572c8db4d.png)

## SP
![image](https://user-images.githubusercontent.com/65912888/88487497-83323e80-cfc0-11ea-86e3-69aa3fde9e4d.png)

2020-07-26 22:26 UTC, dninomiya requested changes

2020-07-26 22:26 UTC, deerboy commented on src/app/app.component.html
> +<app-trending></app-trending>
リモートのmasterをマージして、該当箇所に自分のコンポーネントを設置して欲しいです

2020-07-27 11:02 UTC, kkkkoki commented on src/app/app.component.html
> +<app-trending></app-trending>
マージして該当箇所に設置しましたので、ご確認よろしくお願い致します。

## image
![image](https://user-images.githubusercontent.com/65912888/88534876-e6b18000-d043-11ea-8c83-ad09f20281e9.png)

2020-07-27 11:13 UTC, kkkkoki commented on src/app/app.component.html
> +<app-trending></app-trending>
masterからマージして該当箇所にコンポーネントの設置しましたので、再度ご確認よろしくお願い致します。

## image
![image](https://user-images.githubusercontent.com/65912888/88535767-87546f80-d045-11ea-97d3-cc368cf6de4c.png)

2020-07-27 13:17 UTC, deerboy commented
まだ競合しているようです

2020-07-27 16:33 UTC, kkkkoki commented
もう一度マージし、--prodも削除して競合解決しました。
ご確認よろしくお願い致します！

2020-07-28 01:07 UTC, deerboy commented on src/app/app.component.html
> +<router-outlet></router-outlet>
これは消してOKです！

2020-07-28 01:07 UTC, deerboy commented on src/app/app.component.html
> +    <h2 class="placeholder">TRENDING</h2>
masterで反映されている見出しの作業が無かったことにされているよです...。
競合解決の際、どこを残してどこを消すべきかもう一度確認してみてください。
一度競合解決前まで遡り、再度競合解決を試みてください（練習）

2020-07-28 01:07 UTC, deerboy commented on src/app/trending/trending.component.scss
> +    font-size: 13px;
この対応が抜けているかも

2020-07-28 01:21 UTC, deerboy commented on src/app/app.component.html
> +    <h2 class="placeholder">TRENDING</h2>
消しているわけでは無かったですね。本来カード単体を作ってもらえばOKだったのですが、見出しを含めたエリアごと作っているので、既存のレイアウトや見出しが両立している状態になっています。なので今回自分で作った見出しなどは消して、既存のプレースホルダーとカードを差し替えてもらえればOKです。対応が終わったら自分のローカルで表示チェックを必ずお願いします 👍 

https://github.com/camp-team/team-training/blob/6641c79cb352c9b01c8165eaf333ba59ecec6366/src/app/app.component.html#L29-L31

2020-07-28 10:04 UTC, kkkkoki commented on src/app/app.component.html
> +    <h2 class="placeholder">TRENDING</h2>
不必要な部分の削除と&__dateの対応しましたので、ご確認よろしくお願いします！

2020-07-28 23:47 UTC, dninomiya approved these changes
お疲れ様です！

2020-07-28 23:47 UTC, merged

2020-08-20 01:55 UTC, kkkkoki commented on src/app/trending/trending.component.html
> +    <div
test