Headerマークアップの実装途中
camp-team/team-training pull request #23
Opened 2020-07-26 10:38 UTC by komura-c

実装途中ですが詰まってしまったため、レビューをお願いいたします。

## できない点
- header内のuser-iconのimgが他のheader要素と比べ、ずれてしまうのを修正できない
- header内のuser-iconはdivタグでstyle.background-imageの方がよいと思ったが、実装できない
- nav-list__itemがactiveの時にopacityを1にしようとしたが効かない
- drowerの閉じる実装をどうすれば良いかわからない

お忙しいところ、すみませんが、よろしくお願いいたします。

2020-07-28 06:32 UTC, dninomiya reviewed
レビューしました！

2020-07-28 06:32 UTC, deerboy commented on src/app/app.component.html
>  <div class="placeholder">header</div>
これは消してOKです！

2020-07-28 06:32 UTC, deerboy commented on src/app/header/header.component.html
> +<header class="header" id="js-header">
`[class.active]="isOpen"` 

みたいにしましょう。JSネイティブでElementアクセスは最終手段

2020-07-28 06:32 UTC, deerboy commented on src/app/header/header.component.html
> +  <div class="hamburger" (click)="hamburgerEvent()">
メソッド名は動詞＋目的語

2020-07-28 06:32 UTC, deerboy commented on src/app/header/header.component.html
> +    <span class="hamburger__line hamburger__line--3"></span>
バーガーを動かす場合をのぞいて、SVGでもよかったです！（実装が大変なので）

2020-07-28 06:32 UTC, deerboy commented on src/app/header/header.component.html
> +    </ul>
スマホとPCで二つの要素を設けるのではなく、一つのEleemntがCSSで変化するようにしましょう。二重管理はコストとリスクが増えるので避けたいです

2020-07-28 06:32 UTC, deerboy commented on src/app/header/header.component.ts
> +  bgEvent() {
メソッド名は動詞＋目的語

2020-07-29 16:41 UTC, komura-c commented
レビューありがとうございます！
以下の点を修正いたしました。ご確認よろしくお願いいたします。
- メソッド名をopenDrawer, closeDrawerに変更
- isOpenで--activeクラス付与
- バーガーアイコンをSVGに
- LOGO要素を再利用

2020-07-29 23:56 UTC, dninomiya requested changes
最新のmasterをマージしてください。現在app.component.htmlは大きく変わっているのでヘッダーとフッターとmainさえあればOKな状態になっています。

2020-07-29 23:56 UTC, deerboy commented on src/app/header/header.component.scss
> +    left: -320px;
transform: translateX(-100%)でアニメーションさせましょう

2020-07-29 23:56 UTC, deerboy commented on src/app/header/header.component.html
> +    <img src="/assets/menu-icon.svg">
alt & スラッシュからはじめない

2020-07-29 23:56 UTC, deerboy commented on src/app/header/header.component.html
> +        <a href=""><img src="/assets/home-icon.svg" class="global-nav__img">HOME</a>
img には空でも良いのでaltをつける

2020-07-30 08:40 UTC, komura-c commented
レビューありがとうございます！
以下の点を修正いたしました。ご確認よろしくお願いいたします。

- master確認不足によるマージミスを修正
- transform: translateXでアニメーションを変更
- クリックイベントをhtml側で制御
- imgタグの相対パスを修正、altを追加
- iconをassets/headerフォルダに移動、クリックイベントを修正
- ドロワー位置修正のため、translateXの値を変更

2020-08-03 01:20 UTC, deerboy commented
#2

2020-08-03 01:20 UTC, closed without merging